apiVersion: v1
kind: Service
metadata:
    name: { { include "sso-test.fullname" . } }
    labels: { { - include "sso-test.labels" . | nindent 4 } }
spec:
    type: { { .Values.service.type } }
    ports:
        - port: { { .Values.service.port } }
          targetPort: { { .Values.service.targetPort } }
          protocol: TCP
          name: http
    selector: { { - include "sso-test.selectorLabels" . | nindent 4 } }
