# Default values for sso-test
replicaCount: 3

image:
    repository: your-registry.azurecr.io/sso-test
    pullPolicy: IfNotPresent
    tag: 'latest'

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
    create: true
    annotations: {}
    name: ''

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
    type: ClusterIP
    port: 80
    targetPort: 80

ingress:
    enabled: true
    className: 'nginx'
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    hosts:
        - host: sso-test.example.com
          paths:
              - path: /
                pathType: Prefix
    tls:
        - secretName: sso-test-tls
          hosts:
              - sso-test.example.com

resources:
    limits:
        cpu: 200m
        memory: 256Mi
    requests:
        cpu: 100m
        memory: 128Mi

autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Health checks
healthCheck:
    enabled: true
    path: /health

# Environment variables
env: []

# ConfigMap data
configMap:
    enabled: false
    data: {}

# Secret data
secret:
    enabled: false
    data: {}
